#!/bin/bash

pc=$1

echo \#!/usr/bin/env bash
echo 
echo \#SBATCH --job-name=mx_$pc
echo \#SBATCH --output=out.$pc
echo \#SBATCH --error=err.$pc
echo \#SBATCH -p mistral
echo \#SBATCH --time=02:00:00
echo \#SBATCH --exclusive
echo \#SBATCH --ntasks=$pc
echo \#SBATCH --ntasks-per-node=20
echo \#SBATCH --cpus-per-task 1
echo 
echo 
echo WORKDIR=\${WORKDIR:-\${HOME}/chp-mmk/}
echo MPIEXEC=mpirun
echo 
echo cd \${WORKDIR}
echo . ./.module.load
echo 
echo \${MPIEXEC} -np $pc ./projCHP -X 1000 -Y 1000 -f 0 -x 1.0 -y 1.0 -R 10 -g -v
echo s
